"""Equity research brief rendering, Task 1 bonus.

Markdown is the single source. The HTML page is generated from it rather than written
separately, so the two artefacts cannot drift apart.
"""

import base64
import datetime as dt
from pathlib import Path

import markdown as md_lib
import pandas as pd

from task1_financial.src import charts

DISCLAIMER = (
    "This document is generated by an automated research pipeline for technical "
    "demonstration purposes only. It is not investment advice, not a recommendation to "
    "buy or sell any security, and not a solicitation of any kind. The signal is "
    "produced by a language model reasoning over historical price data and public news "
    "headlines. It has not been reviewed by a licensed analyst. Past performance does "
    "not predict future results, and technical indicators describe what price has "
    "already done rather than what it will do. Anyone acting on this material does so "
    "entirely at their own risk and should consult a qualified financial adviser."
)

SIGNAL_TONE = {"Buy": "buy", "Hold": "hold", "Sell": "sell"}
SENTIMENT_TONE = {"positive": "buy", "negative": "sell", "neutral": "hold"}


def _n(value, dp: int = 2, suffix: str = "", dash: str = "n/a") -> str:
    if value is None or (isinstance(value, float) and pd.isna(value)):
        return dash
    if isinstance(value, (int, float)):
        return f"{value:,.{dp}f}{suffix}"
    return str(value)


def _big(value) -> str:
    if value is None:
        return "n/a"
    for cutoff, unit in ((1e12, "T"), (1e9, "B"), (1e6, "M")):
        if abs(value) >= cutoff:
            return f"{value / cutoff:,.2f}{unit}"
    return f"{value:,.0f}"


def _range_position(summary: dict) -> str:
    price = summary.get("current_price")
    high, low = summary.get("week52_high"), summary.get("week52_low")
    if None in (price, high, low) or high == low:
        return "n/a"
    pct = (price - low) / (high - low) * 100
    return f"{pct:.0f}% of the 52-week range"


def render_markdown(summary: dict, analysis: dict, headlines: list[dict]) -> str:
    ind = summary.get("indicators", {})
    momentum = summary.get("momentum", {})
    agg = analysis.get("aggregate_sentiment")
    signal = analysis.get("signal")
    generated = dt.datetime.now().strftime("%d %B %Y at %H:%M")

    lines = [
        f"# {summary.get('company_name', summary['ticker'])} ({summary['ticker']})",
        "",
        f"Equity research brief, data as of {summary.get('as_of', 'unknown')}. "
        f"Generated {generated}.",
        "",
        "## Company snapshot",
        "",
        "| Metric | Value |",
        "| --- | --- |",
        f"| Current price | {_n(summary.get('current_price'))} {summary.get('currency', '')} |",
        f"| 52-week range | {_n(summary.get('week52_low'))} to {_n(summary.get('week52_high'))} |",
        f"| Position in range | {_range_position(summary)} |",
        f"| P/E ratio | {_n(summary.get('pe_ratio'))} |",
        f"| Market cap | {_big(summary.get('market_cap'))} |",
        f"| Year to date return | {_n(summary.get('ytd_return_pct'), 2, '%')} |",
        f"| Sector | {summary.get('sector') or 'n/a'} |",
        f"| Bars analysed | {summary.get('bars_analysed', 'n/a')} since {summary.get('history_start', 'n/a')} |",
        "",
        "## Technical outlook",
        "",
        "| Indicator | Value |",
        "| --- | --- |",
        f"| SMA 50 | {_n(ind.get('sma_50'))} |",
        f"| SMA 200 | {_n(ind.get('sma_200'))} |",
        f"| RSI 14 | {_n(ind.get('rsi_14'))} |",
        f"| MACD line | {_n(ind.get('macd'), 3)} |",
        f"| MACD signal | {_n(ind.get('macd_signal'), 3)} |",
        f"| MACD histogram | {_n(ind.get('macd_hist'), 3)} |",
        f"| Bollinger upper | {_n(ind.get('bb_upper'))} |",
        f"| Bollinger mid | {_n(ind.get('bb_mid'))} |",
        f"| Bollinger lower | {_n(ind.get('bb_lower'))} |",
        f"| Percent B | {_n(ind.get('bb_pct_b'), 3)} |",
        "",
        f"**Rule-based momentum reading: {momentum.get('signal', 'n/a')}** "
        f"(score {_n(momentum.get('score'), 2)} on a scale of -1 to 1).",
        "",
    ]

    components = momentum.get("components") or {}
    if components:
        readable = ", ".join(
            f"{k.replace('_', ' ')} {'+1' if v > 0 else ('0' if v == 0 else '-1')}"
            for k, v in components.items()
        )
        lines += [f"Components: {readable}.", ""]
    if momentum.get("flags"):
        lines += [f"Flags: {', '.join(momentum['flags'])}.", ""]

    lines += ["## News sentiment", ""]
    if agg:
        lines += [
            f"Aggregate sentiment is **{agg['label']}** at a confidence-weighted score of "
            f"{_n(agg['score'], 3)} on a scale of -1 to 1, across "
            f"{agg['positive'] + agg['negative'] + agg['neutral']} classified headlines "
            f"({agg['positive']} positive, {agg['negative']} negative, {agg['neutral']} neutral) "
            f"with a mean confidence of {_n(agg['mean_confidence'], 2)}.",
            "",
        ]
        rate = analysis.get("classification_success_rate")
        if rate is not None and rate < 1.0:
            lines += [
                f"Note: {len(analysis.get('sentiment_failures', []))} headline(s) failed "
                f"validation and were excluded, a classification success rate of "
                f"{rate * 100:.0f}%.",
                "",
            ]
    else:
        lines += ["No headline sentiment could be retrieved for this run.", ""]

    ranked = sorted(
        analysis.get("headline_sentiment", []),
        key=lambda r: (r["sentiment"] != "neutral", r["confidence"]),
        reverse=True,
    )[:3]
    if ranked:
        lines += ["### Top three headlines", ""]
        for i, r in enumerate(ranked, 1):
            lines += [
                f"{i}. **{r['headline']}**  ",
                f"   *{r['sentiment']}, confidence {r['confidence']:.2f}*. {r['brief_reason']}",
                "",
            ]

    lines += ["## Recommendation", ""]
    if signal:
        lines += [f"### {signal['signal']}", "", signal["justification"], ""]
        if signal.get("key_drivers"):
            lines += ["**Key drivers**", ""]
            lines += [f"- {d}" for d in signal["key_drivers"]]
            lines += [""]
    else:
        lines += [
            "No recommendation was produced for this run.",
            "",
            f"Reason: {analysis.get('signal_error', 'unknown')}.",
            "",
        ]

    lines += ["## Risk disclaimer", "", DISCLAIMER, ""]
    return "\n".join(lines)


CSS = """
:root {
  --surface: #fcfcfb; --panel: #ffffff; --ink: #0b0b0b; --ink-2: #52514e;
  --line: #e5e4e0; --blue: #2a78d6; --red: #e34948; --amber: #eda100;
}
* { box-sizing: border-box; }
body { margin: 0; background: #f2f1ee; color: var(--ink);
  font: 15px/1.65 "Segoe UI", -apple-system, Roboto, Helvetica, Arial, sans-serif; }
.page { max-width: 960px; margin: 32px auto; background: var(--panel);
  border: 1px solid var(--line); border-radius: 10px; padding: 44px 52px 52px; }
h1 { font-size: 28px; margin: 0 0 4px; letter-spacing: -0.015em; }
h2 { font-size: 15px; text-transform: uppercase; letter-spacing: 0.08em;
  color: var(--ink-2); margin: 38px 0 14px; padding-bottom: 8px;
  border-bottom: 1px solid var(--line); }
h3 { font-size: 17px; margin: 22px 0 10px; }
table { width: 100%; border-collapse: collapse; margin: 6px 0 18px; font-size: 14px; }
th { text-align: left; font-weight: 600; color: var(--ink-2); font-size: 12px;
  text-transform: uppercase; letter-spacing: 0.05em; padding: 8px 12px;
  border-bottom: 1px solid var(--line); }
td { padding: 8px 12px; border-bottom: 1px solid #f2f1ee; }
td:last-child { text-align: right; font-variant-numeric: tabular-nums; font-weight: 500; }
tr:last-child td { border-bottom: none; }
.chart { margin: 20px 0 8px; }
.chart img { width: 100%; display: block; border: 1px solid var(--line); border-radius: 8px; }
.verdict { display: inline-block; padding: 7px 18px; border-radius: 999px;
  font-weight: 700; font-size: 15px; letter-spacing: 0.02em; }
.verdict.buy { background: #e6f2fb; color: #1c5cab; }
.verdict.sell { background: #fdecec; color: #a82a29; }
.verdict.hold { background: #fdf3e0; color: #8a5d00; }
.meta { color: var(--ink-2); font-size: 13.5px; margin-bottom: 4px; }
.disclaimer { background: #fdf9ef; border: 1px solid #f0e3c4; border-left: 3px solid var(--amber);
  border-radius: 6px; padding: 16px 20px; font-size: 13px; color: #5c4a1f; line-height: 1.6; }
.disclaimer p { margin: 0; }
ul { padding-left: 20px; } li { margin: 5px 0; }
.footer { margin-top: 32px; padding-top: 14px; border-top: 1px solid var(--line);
  color: var(--ink-2); font-size: 12px; display: flex; justify-content: space-between; }
@media print { body { background: #fff; } .page { border: none; margin: 0; max-width: none; } }
"""


def render_html(markdown_text: str, chart_png: bytes | None, summary: dict, analysis: dict) -> str:
    body = md_lib.markdown(markdown_text, extensions=["tables", "sane_lists"])

    if chart_png:
        encoded = base64.b64encode(chart_png).decode("ascii")
        figure = (
            f'<div class="chart"><img alt="Price with SMA50, SMA200, Bollinger bands, '
            f'RSI and MACD for {summary["ticker"]}" '
            f'src="data:image/png;base64,{encoded}"></div>'
        )
        # Drop the chart in ahead of the technical section it explains.
        marker = "<h2>Technical outlook</h2>"
        body = body.replace(marker, figure + marker, 1) if marker in body else figure + body

    signal = analysis.get("signal")
    if signal:
        tone = SIGNAL_TONE.get(signal["signal"], "hold")
        body = body.replace(
            f"<h3>{signal['signal']}</h3>",
            f'<p><span class="verdict {tone}">{signal["signal"]}</span></p>',
            1,
        )

    body = body.replace("<h2>Risk disclaimer</h2>", '<h2>Risk disclaimer</h2><div class="disclaimer">')
    body = body.rstrip() + "</div>"

    generated = dt.datetime.now().strftime("%d %B %Y %H:%M")
    return f"""<!DOCTYPE html>
<html lang="en"><head><meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>{summary.get('company_name', summary['ticker'])} equity research brief</title>
<style>{CSS}</style></head>
<body><div class="page">{body}
<div class="footer"><span>CDAZZDEV Senior MLE assessment, Task 1</span>
<span>Generated {generated}</span></div>
</div></body></html>"""


def write_report(
    summary: dict, analysis: dict, headlines: list[dict],
    enriched: pd.DataFrame | None = None, output_dir: Path | None = None,
) -> dict[str, Path]:
    output_dir = Path(output_dir or Path(__file__).resolve().parents[1] / "outputs")
    output_dir.mkdir(parents=True, exist_ok=True)
    ticker = summary["ticker"]

    chart_png = None
    if enriched is not None and not enriched.empty:
        chart_png = charts.build_chart(
            enriched, ticker, summary.get("company_name", ticker)
        )

    markdown_text = render_markdown(summary, analysis, headlines)
    html = render_html(markdown_text, chart_png, summary, analysis)

    written = {}
    md_path = output_dir / f"{ticker}_brief.md"
    md_path.write_text(markdown_text, encoding="utf-8")
    written["markdown"] = md_path

    html_path = output_dir / f"{ticker}_brief.html"
    html_path.write_text(html, encoding="utf-8")
    written["html"] = html_path

    if chart_png:
        png_path = output_dir / f"{ticker}_chart.png"
        png_path.write_bytes(chart_png)
        written["chart"] = png_path

    return written
